# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-18 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('type_of', models.CharField(max_length=55, verbose_name='Назначение')),
                ('weight', models.CharField(max_length=55, verbose_name='Вес')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
        ),
    ]
