# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория сладостей')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RenameField(
            model_name='products',
            old_name='type_of',
            new_name='category',
        ),
    ]
