# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190318_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproducts',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='date_published',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
