# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190325_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True, verbose_name='Вес')),
                ('volume', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True, verbose_name='Обьем')),
                ('quantity', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Ingredient', verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingradient',
            field=models.ManyToManyField(to='product.Ingredient'),
        ),
    ]
