# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190331_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingradient',
            field=models.ManyToManyField(blank=True, null=True, to='product.Ingredient'),
        ),
    ]
