# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-14 09:42
from __future__ import unicode_literals

from django.db import migrations
import product.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190413_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, upload_to=product.models.make_upload_path, verbose_name='Фото'),
        ),
    ]
