# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingradient',
            field=models.ManyToManyField(blank=True, to='product.Ingredient'),
        ),
    ]
