# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-14 10:45
from __future__ import unicode_literals

from django.db import migrations
import product.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to=product.models.make_upload_path, verbose_name='Фото'),
        ),
    ]
