# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190505_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Slug'),
        ),
    ]
